// Self-hosts the four faces the design checkpoint chose (OFL licences): asks Google Fonts for the
// variable woff2 of each family's latin subset and writes apps/web/public/fonts plus the @font-face
// sheet. Run once (`node scripts/design/fetch-fonts.mjs`); the files are committed.
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const out = path.join(root, "apps/web/public/fonts");
mkdirSync(out, { recursive: true });
const families = [
  { css: "Bricolage Grotesque", query: "Bricolage+Grotesque:opsz,wght@12..96,200..800", file: "bricolage-grotesque", weight: "200 800" },
  { css: "Manrope", query: "Manrope:wght@200..800", file: "manrope", weight: "200 800" },
  { css: "Caveat", query: "Caveat:wght@400..700", file: "caveat", weight: "400 700" },
  { css: "JetBrains Mono", query: "JetBrains+Mono:wght@100..800", file: "jetbrains-mono", weight: "100 800" },
];
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36";
let sheet = "/* Generated by scripts/design/fetch-fonts.mjs; the faces are OFL and self-hosted. */\n";
for (const f of families) {
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${f.query}&display=swap`, { headers: { "user-agent": UA } })).text();
  // The latin block is the one whose unicode-range starts at U+0000.
  const blocks = css.split("@font-face").slice(1);
  const latin = blocks.find((b) => /unicode-range:\s*U\+0000/.test(b)) ?? blocks[blocks.length - 1];
  const url = latin.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  const range = latin.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  if (!url) throw new Error(`no woff2 for ${f.css}`);
  const bytes = Buffer.from(await (await fetch(url, { headers: { "user-agent": UA } })).arrayBuffer());
  if (bytes.length < 10000 || bytes.subarray(0, 4).toString("ascii") !== "wOF2") throw new Error(`${f.css}: not a woff2 (${bytes.length} bytes)`);
  const name = `${f.file}-latin.woff2`;
  writeFileSync(path.join(out, name), bytes);
  sheet += `@font-face { font-family: "${f.css}"; font-style: normal; font-weight: ${f.weight}; font-display: swap; src: url("/fonts/${name}") format("woff2"); unicode-range: ${range}; }\n`;
  console.log(`${f.css}: ${bytes.length} bytes`);
}
writeFileSync(path.join(root, "apps/web/src/styles/fonts.css"), sheet);
console.log("wrote apps/web/src/styles/fonts.css");
