// docs/design/tokens.json is the source of truth for colour, type, motion and layout; this writes
// the custom properties the web app uses (`node scripts/design/tokens-to-css.mjs`), so a token
// changes in one place. Option A is the site palette the checkpoint decided on.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const t = JSON.parse(readFileSync(path.join(root, "docs/design/tokens.json"), "utf8"));
const kebab = (s) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
const lines = [":root {"];
for (const [k, v] of Object.entries(t.verdict)) lines.push(`  --verdict-${k}: ${v.$value};`);
for (const [k, v] of Object.entries(t.dashboard)) if (v.$type === "color" || v.$type === "dimension") lines.push(`  --cockpit-${kebab(k)}: ${v.$value};`);
for (const [k, v] of Object.entries(t.site.optionA)) if (v.$type === "color") lines.push(`  --site-${kebab(k)}: ${v.$value};`);
for (const [k, v] of Object.entries(t.type)) if (v.$type === "fontFamily") lines.push(`  --font-${k}: ${v.$value.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ")};`);
for (const [k, v] of Object.entries(t.type.scale)) lines.push(`  --size-${kebab(k)}: ${v.$value};`);
lines.push(`  --ease-default: cubic-bezier(${t.motion.easeDefault.$value.join(", ")});`);
lines.push(`  --duration-default: ${t.motion.durationDefault.$value};`);
for (const [k, v] of Object.entries(t.layout)) lines.push(`  --layout-${kebab(k)}: ${v.$value};`);
lines.push("}");
writeFileSync(path.join(root, "apps/web/src/styles/tokens.css"), `/* Generated by scripts/design/tokens-to-css.mjs from docs/design/tokens.json. Do not edit. */\n${lines.join("\n")}\n`);
console.log(`${lines.length - 2} custom properties written`);
